on:
  workflow_dispatch:
  push:
    branches:
      - main

name: SonarCloud

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: |
            ${WORKDIR}/build
            ${WORKDIR}/.gradle/caches
            ${WORKDIR}/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      - name: Install ssh keys
        env:
          SSH_WRITE_PRIVATE: ${{ secrets.SSH_WRITE_PRIVATE }}
          SSH_WRITE_PUBLIC: ${{ secrets.SSH_WRITE_PUBLIC }}
        run: |
          mkdir -p "$HOME/.ssh"
          echo "$SSH_WRITE_PRIVATE" > "$HOME/.ssh/id_ed25519"
          chmod 0700 "$HOME/.ssh/id_ed25519"
          echo "$SSH_WRITE_PUBLIC" > "$HOME/.ssh/id_ed25519.pub"
          chmod 0700 "$HOME/.ssh/id_ed25519.pub"
          eval "$(ssh-agent -s)"
          ssh-add
          git config --global user.email "jens.brimfors@gmail.com"
          git config --global user.name "Jens Brimfors"

      - name: Jacoco report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRC_COM_ACCESS_TOKEN: ${{ secrets.SRC_COM_ACCESS_TOKEN }}
        shell: bash
        run: ./gradlew build jacocoTestReport --stacktrace --info

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=jensim-github
            -Dsonar.projectKey=mega-manipulator
            -Dsonar.coverage.jacoco.xmlReportPaths=${WORKDIR}/build/reports/jacoco/test/jacocoTestReport.xml
            -Dsonar.branch.autoconfig.disabled=true
            -Dsonar.ci.autoconfig.disabled=true
            -X
