on:
  push:
    paths:
      - .github/workflows/sonar.yml
    branches:
      - main

name: SonarCloud

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: |
            ${WORKDIR}/build
            ${WORKDIR}/.gradle/caches
            ${WORKDIR}/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-
      - name: Jacoco report
        shell: bash
        run: ./gradlew build jacocoTestReport
#      - name: SonarCloud Scan
#        uses: sonarsource/sonarcloud-github-action@v1.6
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        with:
#          args: >
#            -Dsonar.organization=jensim-github
#            -Dsonar.projectKey=mega-manipulator
#            -Dsonar.coverage.jacoco.xmlReportPaths=${WORKDIR}/build/reports/jacoco/test/jacocoTestReport.xml
#            -Dsonar.branch.name=main
#            -X
